services:
  container-and-signature-services:
    container_name: container-and-signature-services
    restart: always
    port:
      - '86:8092'
    volumes:
      - C:/dev/docuwere/container-and-signature-services:/confs
    environment:
      - SPRING_CONFIG_LOCATION=/confs/
    image: 'trustlynx/container-signature-service:24.2.1.3'
  dmss-archive-services:
    container_name: dmss-archive-services
    restart: always
    ports:
        - '88:8090'
    volumes:
        - 'C:/dev/docuwere/dmss-archive-services/:/confs'
    environment:
        - SPRING_CONFIG_LOCATION=/confs/
    image: 'trustlynx/dmss-archive-services:24.1.1.5'
  dmss-archive-services-fallback:
    container_name: dmss-archive-services-fallback
    restart: always
    ports:
        - '93:8095'
    volumes:
        - 'C:/dev/docuwere/dmss-archive-services-fallback/:/dmss-archive-services-fallback'
        - 'C:/dev/docuwere/docs:/docs'
    environment:
        - SPRING_CONFIG_LOCATION=/dmss-archive-services-fallback/application.yml
    image: 'trustlynx/dmss-archive-services-fallback:24.0.5'